services:
  novnc_server:
    image: whoatemyapplepie/novnc_server:0.0.0
    build:
      context: dockerfile_devenv
      args:
        - node_version=${node_version}
    container_name: novnc_server
    ports:
      - 5173:5173
      - 8080:8080
    volumes:
      - ../src:/project
    environment:
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
    working_dir: /work
    tty: true
    command: bash /work/startup.sh
